apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject-deployment
  namespace: default
  labels:
    app: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openproject
  template:
    metadata:
      labels:
        app: openproject
    spec:
      initContainers:
      - name: wait-for-postgresdb-connection
        image: postgres:14.7
        ports:
          - containerPort: 5432
        command:  ["sh", "-c", 
        "until pg_isready -h postgres-service.default -p 5432; 
          do echo waiting for database; sleep 2; done;"]                      
      containers:
      - name: openproject
        image: openproject/community:11	
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        env:
        - name: BPFS_STORAGE
          value: "database"        
        - name: AUTO_MIGRATE
          value: "true"                  
        - name: CI_EMAIL
          value: "prueba@gmail.com"                  
        - name: CI_PASSWORD
          value: "hola1234"                  
        - name: DATABASE_URL
          value: "postgres://admin:mysecretpassword@postgres-service.default:5432/openproject"       
        - name: EXTERNAL_URL
          value: "https://demo.localdev.me/"                          