apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-prueba
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:      
      containers:
      - name: postgres
        image: postgres:14.7
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"             
        - name: POSTGRES_USER
          value: "admin"             
        - name: POSTGRES_DB
          value: "openproject" 